version: '3'
services:
  db:
    container_name: mysql_compose
    ports:
      - "3306:3306"
    image: mysql:5.7
    env_file: env_file.txt
    volumes:
      - "mysql_volumes:/var/lib/mysql"
  volumes:
    mysql_volumes: